services:
  blue-app:
    image: proof-of-concept-blue-app:latest
    container_name: blue-app
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  green-app:
    image: proof-of-concept-blue-app:latest
    container_name: green-app
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
