version: '3'
services:
  # Blue Environment (Current Live Version)
  blue:
    build: ./express-test
    container_name: blue-app
    ports:
      - "4002:3000"
    environment:
      - NODE_ENV=production

  # Green Environment (New Version to Deploy)
  green:
    build: ./express-test
    container_name: green-app
    ports:
      - "4001:3000"  # Different port internally for easy access
    environment:
      - NODE_ENV=production

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - blue
      - green
